### PR TITLE
Make html2haml a development-only dependency

### PR DESCRIPTION
**Pull request by aCandidMind**
From all of my understanding, it's only needed in development.
The other lines are only changed because of alignment/indentation for consistency.

I have to admit, that I haven't tested this.

### CODE REVIEW

**Comment by syguer** [comment]
Thank you for PR 👍 
Your idea looks good but I'm concerned that what is 'development'.
`html2haml` might be used on only your application development, but 'development' on 'add_development_dependency' looks meaning this gem development for me 🤔
If it is correct, I think `html2haml` should just be 'add_dependency'.

**Comment by monfresh** [comment]
What I think @aCandidMind  and @voltechs are suggesting is that the only reason `html2haml` would be needed is if someone wanted to convert their HTML or ERB to HAML, which is normally a one-time thing. `haml-rails` doesn't depend on `html2haml` for its main functionality, and therefore should not be considered a main dependency.

Typically, what is done in this situation is to update the README to say that if you want to convert your HTML to HAML, you can run `gem install html2haml` locally, and then run the appropriate commands.

**Comment by daveallie** [comment]
Definitely agreed @monfresh, we're in the process of upgrading our production app to Rails 5.1, and html2haml is still stuck using erubis (which has since been deprecated in favour of erubi). I'd love to remove the deprecation warnings (and html2haml as a whole as we never use it) but haml-rails seems to keep the dependency around for the rake task.

imo it would make more sense to remove html2haml from this package and list instructions on transforming your erb to haml in the readme.

**Comment by inopinatus** [comment]
It should be dropped entirely from the gemspec. File conversion is a not a concern of template rendering.

**Comment by inopinatus** [comment]
In my view haml-rails's ancient dependencies, especially all the unmaintained gems it causes to be installed in production, are entirely unwelcome. I've removed it from production app Gemfiles entirely, replaced by this initializer:

```ruby
# config/initializers/haml.rb

Haml::Template.options[:format] = :html5
ActionView::DependencyTracker.register_tracker :haml, ActionView::DependencyTracker::ERBTracker
```

**Comment by monfresh** [comment]
@amatsuda @olleolleolle Any thoughts on this?

**Comment by olivierlacan** [comment]
This makes sense to me, merging.

**Comment by amatsuda** [comment]
I'm sorry I forgot to reply on this but I like this indeed. ❤️

**Pull request merged**
